export const GET_BRAND = "GET_BRAND";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAILURE = "GET_BRAND_FAILURE";

//Description

export const GET_BRAND_DESCRIPTION = "GET_BRAND_DESCRIPTION ";
export const GET_BRAND_DESCRIPTION_SUCCESS = "GET_BRAND_DESCRIPTION_SUCCESS";
export const GET_BRAND_DESCRIPTION_FAILURE = "GET_BRAND_DESCRIPTION_FAILURE";
