export const GET_CHOCOLATE = "GET_CHOCOLATE";
export const GET_CHOCOLATE_SUCCESS = "GET_CHOCOLATE_SUCCESS";
export const GET_CHOCOLATE_FAILURE = "GET_CHOCOLATE_FAILURE";
//Description

export const GET_CHOCOLATE_DESCRIPTION = "GET_CHOCOLATE_DESCRIPTION ";
export const GET_CHOCOLATE_DESCRIPTION_SUCCESS =
  "GET_CHOCOLATE_DESCRIPTION_SUCCESS";
export const GET_CHOCOLATE_DESCRIPTION_FAILURE =
  "GET_CHOCOLATE_DESCRIPTION_FAILURE";
